### ISSUE TITLE
Find one page bootstrap template

### ISSUE THREAD

**Issue by paragasu** [phisoft/feecollec-web#1]

**Comment by FaziraFM** [comment]
Template 1
https://startbootstrap.com/previews/grayscale

Template 2
https://themewagon.com/themes/hightechit/

Template 3
https://themewagon.com/themes/free-one-page-bootstrap-4-html5-personal-portfolio-website-template-clark/

Template 4
https://startbootstrap.com/previews/stylish-portfolio

Template 5
https://startbootstrap.com/previews/business-casual

Template 6
https://startbootstrap.com/previews/full-width-pics

Template 7
https://themewagon.com/themes/pestkit/

Template 8
https://themewagon.com/themes/free-bootstrap-portfolio-website-template-meyawo/

Template 9
https://www.free-css.com/free-css-templates/page294/woody

Template 10
https://www.free-css.com/free-css-templates/page293/vertex
