### ISSUE TITLE
generate five sets of Q&A for FAQs section

### ISSUE THREAD

**Issue by amyleena95** [phisoft/feecollec-web#12]
The question and answers should be about feecollec and the services we offer for feecollec's customers (support, pricing etc)

Eg:
1. Is the demo free? A: Yes.

**Comment by amyleena95** [comment]
FAQs:
Q1: Our business hours.
A1: Weekdays: 9.00AM - 5.00PM
Weekends: Off

Q2: How do I reach the feecollec's team?
A2: 
- You can reach us at +60 12 873 1819
- You can email us at hello@phisoft.my

Q3: Do I have to pay for the demo?
A3: No. All first demos are free. Subsequent consultations may have additional charges.
 
Q4: Is feecollec easy to use?
A4: Yes. We feature an intuitive user interface and user-friendly workflows, making it accessible for to users of all skill levels.

Q5: Which payment gateways does feecollec integrate with?
A5: feecollec integrates with widely known payment gateways such as Billplz, GHL, FPX, ipay88 and Touch n' Go.

**Comment by Azieyati** [comment]
The five sets of Q&A for FAQs section:

1. How do I get started with FeeCollec's services?
A: Getting started with FeeCollec is easy. Simply visit our website at feecollec.com and schedule a demo. Our team will guide you through the process, answer any questions you may have, and assist you in setting up your account to begin using our services effectively.

2. What types of fees can be managed using FeeCollec?
A: FeeCollec enables property management companies to effortlessly manage various fees associated with property ownership, including maintenance fees and other property-related charges.

3. Does FeeCollec support integration with popular payment gateways?
A: Yes, FeeCollec seamlessly integrates with popular payment gateways, allowing for secure and convenient online payments for property fees.

4. Does FeeCollec offer automated notifications for upcoming payments?
A: Absolutely, FeeCollec includes a notification system that automatically alerts stakeholders about upcoming payments and overdue fees, ensuring timely payments and reducing the risk of missed payments.

5. Can the dashboard in FeeCollec be customized according to user preferences?
A: Yes, FeeCollec offers a customizable dashboard feature, allowing users to tailor their dashboard to display key metrics and insights based on their specific preferences and requirements.


Extra:

6. How can I get assistance if I encounter any issues with FeeCollec?
A: FeeCollec offers comprehensive customer support to assist you with any issues or queries you may have. You can reach out to our support team via email at hello@phisoft.my, and they will be happy to assist you.
