### ISSUE TITLE
change <h1> tags in reasons section to <h3> tag

### ISSUE THREAD

**Issue by amyleena95** [phisoft/feecollec-web#49]
Currently main reasons are using h1 tag.
Replace the h1 tag to h3

![image](https://github.com/phisoft/feecollec-web/assets/43438079/614e7b6d-e836-4753-9e04-f9049b304e26)

- [x] Dashboard
- [x] Property overview
- [x] Invoice overview
- [x] Payment overview

**Comment by sksh70** [comment]
Currently there's no visual difference after changing the tags since it is affected by `font-size: 32px;`

Should I change that? @amyleena95

**Comment by amyleena95** [comment]
Yes. Try 28 first. But keep the h3 tags.
