### ISSUE TITLE
fix responsive UI in iPhone XR dimensions (horizontal)

### ISSUE THREAD

**Issue by amyleena95** [phisoft/feecollec-web#54]
![image](https://github.com/phisoft/feecollec-web/assets/43438079/6839e401-5b87-4cf6-b13b-5256f17617e9)

**Comment by sksh70** [comment]
@amyleena95 this has been fixed in #63 

![image](https://github.com/phisoft/feecollec-web/assets/22228680/004d6daf-8312-43a7-a279-d94504b9299e)
