### ISSUE TITLE
change header photo

### ISSUE THREAD

**Issue by eleysaemily** [phisoft/feecollec-web#58]
- [x] make it related to property, fee 

<img width="1298" alt="image" src="https://github.com/phisoft/feecollec-web/assets/58584270/5c1eb946-41e8-4a59-a8ad-6e6c2345188d">

**Comment by eleysaemily** [comment]
@Azieyati give 5+ suggestions here

**Comment by Azieyati** [comment]
@rosclaritha @eleysaemily Here is a few suggestions for header photo:

1. ![image](https://github.com/phisoft/feecollec-web/assets/156404474/290a1697-0c90-4bb7-bb9b-5accd7da8645)

2. ![image](https://github.com/phisoft/feecollec-web/assets/156404474/e04275c9-dd84-4ae2-be74-ed8f5b2f667c)

3. ![image](https://github.com/phisoft/feecollec-web/assets/156404474/7e27b8c8-5b8b-4cfe-a6e2-8d0ce87c5c9c)

4. ![image](https://github.com/phisoft/feecollec-web/assets/156404474/89240aa6-3bd0-49f5-9ce9-c7fc340f945b)

5. ![image](https://github.com/phisoft/feecollec-web/assets/156404474/e020302e-897b-40dd-b0b9-87fb7d469aac)

6. ![image](https://github.com/phisoft/feecollec-web/assets/156404474/278d8d76-94a8-43eb-aaeb-283d2a10e5b8)

**Comment by eleysaemily** [comment]
@paragasu more suggestion for #86

**Comment by eleysaemily** [comment]
@Azieyati please give more suggestions

**Comment by sksh70** [comment]
@eleysaemily @paragasu Here's my suggestions

![feecollec](https://github.com/phisoft/feecollec-web/assets/22228680/4ec96364-5e7f-4bf0-86c0-f72154514d83)

**Comment by eleysaemily** [comment]
@sksh70 example:
<img width="1437" alt="image" src="https://github.com/phisoft/feecollec-web/assets/58584270/f320b59e-a123-49cd-a854-5dfd26e79b31">
