### ISSUE TITLE
Find suitable image for banner background image

### ISSUE THREAD

**Issue by paragasu** [phisoft/feecollec-web#86]
<img width="1608" alt="image" src="https://github.com/phisoft/feecollec-web/assets/27353/a1d10ccf-9e54-4dc2-9e47-c6bae9d990ac">

**Comment by AzmirMuda** [comment]
Hii here some image for banner background
![Screenshot (247)](https://github.com/phisoft/feecollec-web/assets/118720025/0718ba33-4457-4ab4-a142-15bd5f5cae42)
![Screenshot (243)](https://github.com/phisoft/feecollec-web/assets/118720025/6b2ceace-a4c8-4c42-ab10-7b2f75ac861c)
![Screenshot (248)](https://github.com/phisoft/feecollec-web/assets/118720025/9131523a-6dbc-48c2-8fef-f5c545c8b628)
![Screenshot (249)](https://github.com/phisoft/feecollec-web/assets/118720025/c9adc0fd-f182-4245-bb7e-7be605e91f73)
