### ISSUE TITLE
find suitable business background for FAQs section

### ISSUE THREAD

**Issue by amyleena95** [phisoft/feecollec-web#91]
- minimal shapes, eg geometric etc

can give 3 - 5 suggestions first

**Comment by Azieyati** [comment]
@amyleena95  Here is a few suggestion for FAQs section:


Suggest 1:
![bg1](https://github.com/phisoft/feecollec-web/assets/156404474/970ad39f-35a5-47a3-8b5d-e50a4193f448)

output:
![Screenshot 2024-04-09 142507](https://github.com/phisoft/feecollec-web/assets/156404474/ca342907-1ee0-45ef-b45a-610e528de6ec)



Suggest 2:
![bg2](https://github.com/phisoft/feecollec-web/assets/156404474/ff22dd30-2daa-4b4b-8dd0-2dfaad1ffd39)
output:

![Screenshot 2024-04-09 142910](https://github.com/phisoft/feecollec-web/assets/156404474/0ff875e0-7cd2-42c3-aea5-3cd258b5b819)



Suggest 3:
![bg3](https://github.com/phisoft/feecollec-web/assets/156404474/1e0e7c02-bb1a-40e8-b8b9-021e1f710b01)
output:
![Screenshot 2024-04-09 142925](https://github.com/phisoft/feecollec-web/assets/156404474/b722e1f1-9f27-44e5-afbe-e5712495988f)



Suggest 4:
![bg4](https://github.com/phisoft/feecollec-web/assets/156404474/98e8b099-c1eb-43c5-8881-78a78ab3a4a5)
output:
![Screenshot 2024-04-09 143002](https://github.com/phisoft/feecollec-web/assets/156404474/ac063183-b001-4d24-acf4-332dcda0f92b)



Suggest 5:
![bg6](https://github.com/phisoft/feecollec-web/assets/156404474/93384337-9f06-4e77-807e-7f875f3b33df)
output:
![Screenshot 2024-04-09 143025](https://github.com/phisoft/feecollec-web/assets/156404474/3631ad04-81d0-4bdb-8c5f-2c8920d5529b)



Suggest 6:
![bg7](https://github.com/phisoft/feecollec-web/assets/156404474/292bf9b6-6629-4b02-82f2-6362dd22d067)
output:
![image](https://github.com/phisoft/feecollec-web/assets/156404474/3189c095-be58-4b6a-b853-231b6f01ab16)
