### ISSUE TITLE
change demo section UI

### ISSUE THREAD

**Issue by amyleena95** [phisoft/feecollec-web#95]
![image](https://github.com/phisoft/feecollec-web/assets/43438079/80932d95-060d-4bf4-ab71-06de32aaabcb)

**Comment by amyleena95** [comment]
> @amyleena95 How about this?
> 
> 
> 
> ![Untitled](https://github.com/phisoft/feecollec-web/assets/22228680/fc8ff890-54e9-49f2-b770-7a73a9d28b7c)
> 
> 

No need to add map first. Just commit the updated wording.

**Comment by sksh70** [comment]
ok I thought need new design

**Comment by amyleena95** [comment]
Ok. We’ll just kiv the map part. 👍
